@echo off
set FANTASEE_LIBRARY_AGENT=0
set FANTASEE_GENERATION_RECOVERY_DELAY=86400
set FANTASEE_LIBRARY_AGENT_START_DELAY=86400
set FANTASEE_LIBRARY_AGENT_INTERVAL=86400
cd /d C:\dev\fantasee
C:\Python314\python.exe server.py
